version: '3.8'

services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      - ALLOW_ORIGINS
      - OPENAI_API_KEY
      - MODEL
      - EMBEDDING_MODEL
      - EMBEDDING_DIMENSIONS
      - REDIS_HOST
      - REDIS_PORT
      - DOCS_DIR
      - EXPORT_DIR
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  redis:
    image: redislabs/redisearch:latest
    volumes:
      - redis_data:/data
    networks:
      - mynetwork

volumes:
  redis_data:

networks:
  mynetwork:
    driver: bridge