version: '3.8'

services:
  app:
    build: .
    environment:
      - ALLOW_ORIGINS
      - OPENAI_API_KEY
      - MODEL
      - EMBEDDING_MODEL
      - EMBEDDING_DIMENSIONS
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_PORT2
      - DOCS_DIR
      - EXPORT_DIR
    ports:
      - "8080:8000"
    restart: always
    networks:
      - mynetwork

volumes:
  redis_data:

networks:
  mynetwork:
    driver: bridge